module_13/icollector/icollector/urls.py
from django.contrib import admin
from django.urls import path, include
from products.views import IndexView
from django.conf import settings
from django.conf.urls.static import static
from orders.views import stripe_web_hook

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", IndexView.as_view(), name="index"),
    path("products/", include("products.urls", namespace="products")),
    path("users/", include("users.urls", namespace="users")),
    path("orders/", include("orders.urls", namespace="orders")),
    path('webhook/stripe/', stripe_web_hook, name='stripe_webhook'),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

module_13/icollector/orders/urls.py
from django.urls import path
from orders.views import OrderCreateView, SuccessTemplateView, CanceledTemplateView, OrderListView, OrderDetailView
app_name = "orders"

urlpatterns = [
    path('order-create/', OrderCreateView.as_view(), name="order_create"),
    path('', OrderListView.as_view(), name="orders_list"),
    path('order/<int:pk>/', OrderDetailView.as_view(), name="order"),
    path('order-success/', SuccessTemplateView.as_view(), name="order_success"),
    path('order-canceled/', CanceledTemplateView.as_view(), name="order_canceled"),
]

module_13/icollector/products/urls.py
from django.urls import path
from . import views

app_name = "products"

urlpatterns = [
    path("", views.ProductListView.as_view(), name="products"),
    path("baskets/add/<int:product_id>/", views.basket_add, name="basket_add"),
    path("baskets/remove/<int:basket_id>/", views.basket_remove, name="basket_remove"),
    path("page/<int:page>", views.ProductListView.as_view(), name="paginator"),
    path("category/<int:category_id>/", views.ProductListView.as_view(), name="category"),
]

module_13/icollector/users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.contrib.auth.decorators import login_required
from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('profile/<int:pk>/', login_required(views.ProfileView.as_view()), name='profile'),
    path('registration/', views.RegistrationView.as_view(), name='registration'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('verify/<str:email>/<uuid:code>/', views.EmailVerificationView.as_view(), name='email_verification'),
]

module_13/icollector/products/models.py
from django.db import models
from users.models import User
import stripe
from django.conf import settings

stripe.api_key = settings.STRIPE_SECRET_KEY


class ProductCategory(models.Model):
    name = models.CharField(max_length=50, unique=True)
    description = models.CharField(max_length=250, null=True, blank=True)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    quantity = models.PositiveSmallIntegerField(default=0)
    image = models.ImageField(upload_to='products_images')
    stripe_product_price_id = models.CharField(max_length=200, null=True, blank=True)
    category = models.ForeignKey(to=ProductCategory, on_delete=models.CASCADE)

    def __str__(self):
        return f'Product: {self.name} | Category: {self.category.name}'

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.stripe_product_price_id:
            self.stripe_product_price_id = self.create_stripe_product_price()['id']
        super().save(force_insert, force_update, using, update_fields)

    def create_stripe_product_price(self):
        stripe_product = stripe.Product.create(name=self.name)
        stripe_product_price = stripe.Price.create(
            product=stripe_product['id'],
            unit_amount=round(self.price * 100),
            currency='usd'
        )
        return stripe_product_price


class BasketQuerySet(models.QuerySet):
    def total_sum(self):
        return sum(basket.sum() for basket in self)

    def total_quantity(self):
        return sum(basket.quantity for basket in self)

    def stripe_products(self):
        line_items = []
        for basket in self:
            item = {
                'price': basket.product.stripe_product_price_id,
                'quantity': basket.quantity,
            }
            line_items.append(item)
        return line_items


class Basket(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    objects = BasketQuerySet.as_manager()

    def __str__(self):
        return f'Basket for {self.user.username} | Product: {self.product.name}'

    def sum(self):
        return self.product.price * self.quantity

    def de_json(self):
        basket_item = {
            'product_name': self.product.name,
            'quantity': self.quantity,
            'price': float(self.product.price),
            'sum': float(self.sum()),
        }
        return basket_item

module_13/icollector/products/views.py
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.shortcuts import HttpResponseRedirect, redirect
from common.views import TitleMixin
from .models import Product, ProductCategory, Basket
from django.contrib.auth.decorators import login_required


class IndexView(TitleMixin, TemplateView):
    title = 'Home - iCollector'
    template_name = 'products/index.html'


class ProductListView(TitleMixin, ListView):
    title = 'Products - iCollector'
    template_name = 'products/products.html'
    model = Product
    paginate_by = 6

    def get_queryset(self):
        queryset = super().get_queryset()
        category_id = self.kwargs.get('category_id')
        queryset = Product.objects.filter(category_id=category_id) if category_id else queryset
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = ProductCategory.objects.all()
        return context

@login_required
def basket_add(request, product_id):
    baskets = Basket.objects.filter(user=request.user, product_id=product_id)
    if baskets.exists():
        basket = baskets.first()
        basket.quantity += 1
        basket.save()
    else:
        product = Product.objects.get(id=product_id)
        Basket.objects.create(user=request.user, product=product, quantity=1)
    if request.META.get('HTTP_REFERER'):
        return redirect(request.META['HTTP_REFERER'])
    return redirect(to="products:products")

@login_required
def basket_remove(request, basket_id):
    basket = Basket.objects.get(id=basket_id)
    basket.delete()
    return redirect(to=request.META['HTTP_REFERER'])

module_13/icollector/products/templates/products/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title%}{% endblock %}</title>

    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/css/base.css' %}" rel="stylesheet"/>
    {% block css%}
    {% endblock %}

</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="\">Apple iCollector</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:products' %}">Catalog <i class="fas fa-shopping-bag"></i> </a>
                </li>
                {% if user.is_authenticated %}
                    {% if baskets %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:profile' user.id %}"><i class="fas fa-shopping-cart"></i><span class='badge badge-warning' id='lblCartCount'> {{ baskets.total_quantity }} </span> </a>
                    </li>
                {% endif %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fas fa-user-circle"></i>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>
                                <a class="dropdown-item" href="{% url 'users:profile' user.id %}">Profile</a>
                            </li>
                            <li><a class="dropdown-item" href="{% url 'orders:orders_list' %}">Orders</a></li>
                            {% if user.is_superuser or user.is_staff %}
                                <li><a class="dropdown-item" href="{% url 'admin:index' %}">Admin-panel</a></li>
                            {% endif %}
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'users:logout' %}">
                                    Log out
                                </a>
                            </li>
                        </ul>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Log in <i class="fas fa-sign-in-alt"></i></a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
{% block content %}
{% endblock %}

{% block footer %}
{% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

</body>

</html>

module_13/icollector/products/templates/products/baskets.html
{% load humanize %}
{% if baskets %}
    <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
                Basket <span class="badge badge-secondary badge-pill">{{ baskets.total_quantity }}</span>
            </h4>
{% for basket in baskets %}
<div class="card mb-3">
    <div class="card-body">
        <h5 class="card-title">{{ basket.product.name }}</h5>
        <p class="card-text">{{ basket.product.description }}</p>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item bg-light">
            <div class="row text-center">
                <div class="col-lg-4">
                    <input name="basketID" type="number" class="form-control"
                           value="{{ basket.quantity }}" min="1">
                </div>
                <div class="col-lg-4">$ {{ basket.sum|intcomma }}</div>
                <div class="col-lg-4">
                    <a href="{% url 'products:basket_remove' basket.id %}">
                        <i class="fas fa-trash"></i>
                    </a>
                </div>
            </div>
        </li>
    </ul>
</div>
    {% endfor %}
<div class="card mb-3">
    <div class="card-footer">
        <p class="float-left">Total</p>
        <h4 class="float-right">$ {{ baskets.total_sum|intcomma }}</h4>
    </div>
</div>
<a class="btn btn-success btn-lg float-right" href="{% url 'orders:order_create' %}">
    Checkout
</a>
{% else %}
        <h4 class="mt-3 mb-3 text-center ">
                Basket is empty
            </h4>
{% endif %}

module_13/icollector/products/templates/products/index.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
<link href="{% static 'vendor/css/index.css' %}" rel="stylesheet"/>
{% endblock %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h1 class="mt-5">iCollector</h1>
                    <p>
                        The best way to buy the products you love.
                    </p>
                    <button id="start-purchase-btn" type="button" class="btn btn-lg">
                        <a id="start-purchase-link" href="{% url 'products:products' %}">
                            Start shopping
                        </a>
                    </button>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

module_13/icollector/products/templates/products/products.html
{% extends "products/base.html" %}
{% load static %}
{% load humanize %}
{% load cache %}

{% block title %}{{title}}{% endblock %}

{% block css %}
<link href="{% static 'vendor/css/products.css' %}" rel="stylesheet">
{% endblock %}


{% block content %}
<div class="container">

    <div class="row">

        <div class="col-lg-3">
            <br />
            <div class="list-group">
                {% for category in categories %}
                    <a href="{% url 'products:category' category.id %}" class="list-group-item">{{category.name}}</a>
                {% endfor %}
            </div>

        </div>

        <div class="col-lg-9">

            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-1.png' %}" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-2.png' %}" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-3.png' %}" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <div class="row">
            {% cache 30 object_list %}
            {% for product in object_list %}
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="#">
                            <img class="card-img-top"
                                 src="{{product.image.url}}"
                                 alt="">
                        </a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="#">{{product.name}}</a>
                            </h4>
                            <h5>${{product.price|intcomma}}</h5>
                            <p class="card-text">{{product.description}}</p>
                        </div>
                        <div class="card-footer text-center">
                            <a class="btn btn-outline-success" href="{% url 'products:basket_add' product.id %}">
                                Додати в кошик
                            </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
            {% endcache %}
            </div>
            {% if is_paginated %}
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                        <a class="page-link"
                           href="{% if page_obj.has_previous %} {% url 'products:paginator' page_obj.previous_page_number %} {% else %} # {% endif %}"
                           tabindex="-1" aria-disabled="true">
                            Previous
                        </a>
                    </li>
                {% for page in paginator.page_range %}
                    <li class="page-item"><a class="page-link" href="{% url 'products:paginator' page %}">{{ page }}</a></li>
                {% endfor %}
                    <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
                        <a class="page-link"
                           href="{% if page_obj.has_next %} {% url 'products:paginator' page_obj.next_page_number %} {% else %} # {% endif %}">
                            Next
                        </a>
                    </li>
                </ul>
            </nav>
            {% endif %}
        </div>

    </div>

</div>
{% endblock %}

{% block footer %}
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Store 2023</p>
    </div>
</footer>
{% endblock %}