module_13/icollector/icollector/urls.py
from django.contrib import admin
from django.urls import path, include
from products.views import IndexView
from django.conf import settings
from django.conf.urls.static import static
from orders.views import stripe_web_hook

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", IndexView.as_view(), name="index"),
    path("products/", include("products.urls", namespace="products")),
    path("users/", include("users.urls", namespace="users")),
    path("orders/", include("orders.urls", namespace="orders")),
    path('webhook/stripe/', stripe_web_hook, name='stripe_webhook'),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

module_13/icollector/orders/urls.py
from django.urls import path
from orders.views import OrderCreateView, SuccessTemplateView, CanceledTemplateView, OrderListView, OrderDetailView
app_name = "orders"

urlpatterns = [
    path('order-create/', OrderCreateView.as_view(), name="order_create"),
    path('', OrderListView.as_view(), name="orders_list"),
    path('order/<int:pk>/', OrderDetailView.as_view(), name="order"),
    path('order-success/', SuccessTemplateView.as_view(), name="order_success"),
    path('order-canceled/', CanceledTemplateView.as_view(), name="order_canceled"),
]

module_13/icollector/users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.contrib.auth.decorators import login_required
from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('profile/<int:pk>/', login_required(views.ProfileView.as_view()), name='profile'),
    path('registration/', views.RegistrationView.as_view(), name='registration'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('verify/<str:email>/<uuid:code>/', views.EmailVerificationView.as_view(), name='email_verification'),
]

module_13/icollector/orders/models.py
from django.db import models
from users.models import User
from products.models import Basket


class Order(models.Model):
    CREATED = 0
    PAID = 1
    ON_WAY = 2
    DELIVERED = 3
    STATUSES = (
        (CREATED, 'Created'),
        (PAID, 'Paid'),
        (ON_WAY, 'On way'),
        (DELIVERED, 'Delivered'),
    )

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    address = models.CharField(max_length=256)
    basket_history = models.JSONField(default=dict)
    created = models.DateTimeField(auto_now_add=True)
    status = models.SmallIntegerField(default=CREATED, choices=STATUSES)
    initiator = models.ForeignKey(to=User, on_delete=models.CASCADE)

    def __str__(self):
        return f'Order #{self.id} {self.first_name} {self.email}'

    def update_after_payment(self):
        baskets = Basket.objects.filter(user=self.initiator)
        self.status = self.PAID
        self.basket_history = {
            'purchased_items': [basket.de_json() for basket in baskets],
            'total_sum': float(baskets.total_sum()),
        }
        baskets.delete()
        self.save()

module_13/icollector/orders/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Bob',
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Hill',
    }))
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'example@gmail.com',
    }))
    address = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Ukraine, Kiev, Soborna Street 100',
    }))

    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address']

module_13/icollector/orders/views.py
from django.http import HttpResponseRedirect, HttpResponse
from http import HTTPStatus
from django.urls import reverse_lazy, reverse
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from common.views import TitleMixin
from products.models import Basket
from django.conf import settings
from .models import Order
from .forms import OrderForm
from django.views.decorators.csrf import csrf_exempt
import stripe


class OrderListView(TitleMixin, ListView):
    template_name = 'orders/orders.html'
    title = 'Orders - iCollector'
    model = Order
    ordering = '-created'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(initiator=self.request.user)


class OrderCreateView(TitleMixin, CreateView):
    title = 'iCollector - Ordering'
    template_name = 'orders/order-create.html'
    form_class = OrderForm
    success_url = reverse_lazy('orders:order_create')

    def post(self, request, *args, **kwargs):
        super().post(request, *args, **kwargs)
        baskets = Basket.objects.filter(user=self.request.user)
        checkout_session = stripe.checkout.Session.create(
            line_items=baskets.stripe_products(),
            metadata={'order_id': self.object.id},
            mode='payment',
            success_url='{}{}'.format(settings.DOMAIN_NAME, reverse('orders:order_success')),
            cancel_url='{}{}'.format(settings.DOMAIN_NAME, reverse('orders:order_canceled')),
        )
        return HttpResponseRedirect(checkout_session.url, status=HTTPStatus.SEE_OTHER)

    def form_valid(self, form):
        form.instance.initiator = self.request.user
        return super().form_valid(form)


class OrderDetailView(DetailView):
    template_name = 'orders/order.html'
    model = Order

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'iCollector - Order #{self.object.id}'
        return context


class SuccessTemplateView(TitleMixin, TemplateView):
    template_name = 'orders/success.html'
    title = 'iCollector - Thanks for ordering'


class CanceledTemplateView(TemplateView):
    template_name = 'orders/canceled.html'


@csrf_exempt
def stripe_web_hook(request):
    payload = request.body
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']
    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, settings.STRIPE_WEBHOOK_SECRET
        )
    except ValueError as e:
        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError as e:
        return HttpResponse(status=400)

    if event['type'] == 'checkout.session.completed':
        session = event['data']['object']
        fulfill_order(session)

    return HttpResponse(status=200)


def fulfill_order(session):
    order_id = int(session.metadata.order_id)
    order = Order.objects.get(id=order_id)
    order.update_after_payment()
    print("Fulfilling order")

module_13/icollector/orders/templates/orders/canceled.html
<!DOCTYPE html>
<html>
<head>
  <title>Checkout canceled</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <section>
    <p>Forgot to add something to your cart? Shop around then come back to pay!</p>
  </section>
</body>
</html>

module_13/icollector/orders/templates/orders/order-create.html
{% extends "products/base.html" %}
{% load humanize %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <section>
    <div class="alert alert-warning text-center" role="alert">
        Please fill in your email address.
    </div>
    <div class="container">
        <div class="py-5 text-center">
            <h1>Checkout</h1>
        </div>
        <div class="row g-5">
            <div class="col-md-5 col-lg-4 order-md-last">
                <h4 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-primary">Basket</span>
                    <span class="badge badge-primary badge-pill text-white">{{ baskets.total_quantity }}</span>
                </h4>
                <ul class="list-group mb-3">
                    {% for basket in baskets %}
                        <li class="list-group-item d-flex justify-content-between lh-sm">
                        <div>
                            <h6 class="my-0">{{ basket.product.name }}</h6>
                            <small class="text-muted">{{ basket.quantity }}</small>
                        </div>
                        <span class="text-muted">$ {{ basket.sum|intcomma }}</span>
                    </li>
                    {% endfor %}
                    <li class="list-group-item d-flex justify-content-between">
                        <span>Amount payable</span>
                        <strong>$ {{ baskets.total_sum|intcomma }}</strong>
                    </li>
                </ul>
            </div>
            <div class="col-md-7 col-lg-8">
                <h4 class="mb-3">Delivery address</h4>
                <form action="{% url 'orders:order_create' %}", method="post">
                    {% csrf_token %}
                    <div class="row g-3">
                        <div class="col-sm-6">
                            <label for="{{ form.first_name.id_for_label }}" class="form-label">First Name</label>
                            {{ form.first_name }}
                        </div>

                        <div class="col-sm-6">
                            <label for="{{ form.last_name.id_for_label }}" class="form-label">Last Name</label>
                            {{ form.last_name }}
                        </div>

                        <div class="col-12 mt-3">
                            <label for="{{ form.email.id_for_label }}" class="form-label">Email</label>
                            {{ form.email }}
                        </div>

                        <div class="col-12 mt-3">
                            <label for="{{ form.address.id_for_label }}" class="form-label">Address</label>
                            {{ form.address }}
                        </div>

                    </div>

                    <hr class="my-4">

                    <button class="w-100 btn btn-primary btn-lg" type="submit">Continue</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

module_13/icollector/orders/templates/orders/order.html
{% extends "products/base.html" %}
{% load humanize %}

{% block content %}
<section>
    <div class="container pt-5">
        <div class="text-center mt-5">
            <h1>Order #{{ object.id }}</h1>
            <div class="orders mt-5">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Price</th>
                        <th scope="col">Sum</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for purchased_item in object.basket_history.purchased_items %}
                    <tr>
                        <th scope="row">
                           {{ purchased_item.product_name }}
                        </th>
                        <td>{{ purchased_item.quantity }}</td>
                        <td>$ {{ purchased_item.price|intcomma }}</td>
                        <td>$ {{ purchased_item.sum|intcomma }}</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <p class="float-right h4 mt-3">Total $ {{ object.basket_history.total_sum|intcomma }}</p>
            </div>
        </div>
    </div>
</section>
{% endblock %}

module_13/icollector/orders/templates/orders/orders.html
{% extends "products/base.html" %}
{% load humanize %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<section>
    <div class="container pt-5">
        <div class="text-center mt-5">
            <h1>Orders</h1>
            <div class="orders mt-5">
                <table class="table">
                    <thead>
                    <tr class="table-light">
                        <th scope="col">#</th>
                        <th scope="col">Status</th>
                        <th scope="col">Created</th>
                        <th scope="col">Total</th>
                        <th scope="col">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for order in object_list %}
                    <tr>
                        <th scope="row">{{ order.id }}</th>
                        <td>{{ order.get_status_display }}</td>
                        <td>{{ order.created|naturaltime}}</td>
                        <td>$ {{ order.basket_history.total_sum|intcomma }}</td>
                        <td>
                            <a href="{% url 'orders:order' order.id %}">View</a>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
{% endblock %}

module_13/icollector/orders/templates/orders/success.html
{% extends 'users/base.html' %}

{% block content %}

<main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header">
                                <h3 class="text-center font-weight-light my-4">Thank you for the order!</h3>
                            </div>
                            <div class="card-body text-center">
                                <h4>
                                    Your order has been successfully generated.
                                </h4>
                            </div>
                            <div class="card-footer text-center">
                                <a class="btn btn-outline-success" href="{% url 'orders:orders_list' %}">My Orders</a>
                                <a class="btn btn-outline-success" href="{% url 'index' %}">Go Home</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>

{% endblock %}